name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs every time you push to the main branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          VITE_SERVICEID: ${{ secrets.VITE_SERVICEID }}
          VITE_TEMPLATEID: ${{ secrets.VITE_TEMPLATEID }}
          VITE_PUBLICKEY: ${{ secrets.VITE_PUBLICKEY }}
          VITE_TEMPLATEIDII: ${{ secrets.VITE_TEMPLATEIDII }}
          VITE_SERVICEIDII: ${{ secrets.VITE_SERVICEIDII }}
          VITE_PRIVATEKEY: ${{ secrets.VITE_PRIVATEKEY }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Change to 'build' if you are using Create React App instead of Vite
          branch: gh-pages